
<script lang="ts">/**
    THIS FILE IS AUTOGENERATED. DO NOT MODIFY.
    IT WILL BE OVERWRITTEN ON THE NEXT BUILD.
**/
    import {Article} from "$local/article";
    import {_MC_Join as ArticleData } from "$lib/generated/posts";
</script>
<Article {...ArticleData}/>
