name: Deploy to GitHub Pages

on:
  push:
    branches: 'master'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun.js
        uses: oven-sh/setup-bun@v1 # Official Bun action
        with:
          bun-version: latest # Or specify a version e.g., '1.0.0'

      - name: Install dependencies
        run: bun install --frozen-lockfile # Recommended for CI for reproducible builds

      - name: Compile articles
        run: bun run ./articles/build.ts

      - name: Build site
        env:
          BASE_PATH: '/'
        run: bun run build # Assuming your build script is defined in package.json scripts

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
